spring:
  cloud:
    consul:
      host: 192.168.170.3
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 15s
        hostname: 192.168.0.106
      config:
        fail-fast: true
        format: YAML
        prefix: config
        default-context: application
        profile-separator: ','
        data-key: data
  profiles:
    active: dev
  application:
    name: cloud-admin
server:
  port: 8084
feign:
  hystrix:
    enabled: true