spring:
  cloud:
    consul:
      host: 192.168.170.3
      port: 8500
      discovery:
        health-check-path: /health
        health-check-interval: 15s
        instance-id: cloud01-id
        hostname: 192.168.0.106
  application:
    name: cloud02-application
server:
  port: 50124